unknown = Unknown
show-more = Show more
next = Next
levels = Levels
rankings = Rankings
references = References
account-settings = Account settings
upload-level = Submit level
submit = Submit
table-of-contents = Table of Contets
my-levels = 내 레벨
back = 돌아가기
