create-item = Add “{ $value }” to list
music-title-subtitle = Featuring artists must also be included in the title. If you don't see your song in the list, add it yourself!
upload-level-disclaimer = Infringements of others' copyrights or other rights may result in rejection of your level and punishment according to relevant laws.
appending-title-subtitle = Please enter if you have a subtitle, such as (EX) or (Nerfed).
creator-alias-placeholder = Enter creator alias
creator-alias-subtitle = Enter if you need to display another name instead, such as a team name.
preparing-upload = Preparing to upload...
music-title = Music Title
upload-level-title = Drag and drop { "." }zip file
basic-information = Basic Info
artists = Artists
create-level = Submit Level
upload-level-subtitle = or click here to select file
appending-title-placeholder = Enter level subtitle
appending-title = Level Subtitle
creators = Creators
creator-alias = Creator Alias
add = Add
music-title-placeholder = Enter music title...
creators-subtitle = Only users with an ADOFAI.gg account can add.
display-information = Displayed Info
level-information = Level Info
video-url = YouTube Video Link
video-url-subtitle = 레벨 전체를 녹화하고 YouTube에 업로드한 영상의 링크를 입력하세요.
video-url-placeholder = Enter video link
workshop-url = Steam Workshop Link
workshop-url-placeholder = Enter Workshop link
thumbnail = Thumbnail
thumbnail-subtitle = 설정하지 않으면 영상 썸네일이 적용됩니다. 사진에 대한 권리가 있는지 확인하세요. 최대 4MB까지 업로드할 수 있습니다.
change-thumbnail = Change
thumbnail-drop-to-change = Drag here to change thumbnail
reset-thumbnail = Use video thumbnail
description = Level Description
description-subtitle = 2,000 characters max.
description-placeholder = Enter description
tiles = Tile Count
tiles-subtitle = 레벨 에디터에서 Ctrl + F (⌘ + F)를 눌러 타일 번호를 확인할 수 있습니다.
tiles-placeholder = 타일 수 입력
bpm = 기본 BPM
bpm-subtitle = 노래의 기본 BPM을 입력하세요.
min-bpm = 최소 BPM
max-bpm = 최대 BPM
expected-difficulty = 예상 난도
expected-difficulty-subtitle = 책정할 때의 참고용으로만 사용됩니다.
expected-difficulty-placeholder = 난도 선택
leave-alert = 레벨 투고를 취소하고 이 페이지에서 나갈까요?
limits = 제약 사항
limits-subtitle = 레벨을 플레이하는 데 제약 사항이 있다면 선택하세요.
limits-neocosmos = Neo Cosmos DLC 필요
limits-seizure = 광과민성 발작 가능성
submitting = 레벨을 제출하는 중...
submit-success = 레벨 제출이 완료되었습니다.
uploading = 업로드 중...
