create-item = Add “{ $value }” to list
music-title-subtitle = Featuring artists must also be included in the title. If you don't see your song in the list, add it yourself!
upload-level-disclaimer = Infringements of others' copyrights or other rights may result in rejection of your level and punishment according to relevant laws.
appending-title-subtitle = Please enter if you have a subtitle, such as (EX) or (Nerfed).
creator-alias-placeholder = Enter creator alias
creator-alias-subtitle = Enter if you need to display another name instead, such as a team name.
preparing-upload = Preparing to upload...
music-title = Music Title
upload-level-title = Drag and drop { "." }zip file
basic-information = Basic Info
artists = Artists
create-level = Submit Level
upload-level-subtitle = or click here to select file
appending-title-placeholder = Enter level subtitle
appending-title = Level Subtitle
creators = Creators
creator-alias = Creator Alias
add = Add
music-title-placeholder = Enter music title...
creators-subtitle = Only users with an ADOFAI.gg account can add.
display-information = Displayed Info
level-information = Level Info
video-url = YouTube Video Link
video-url-subtitle = Enter the YouTube link to a full recording of your level.
video-url-placeholder = Enter video link
workshop-url = Steam Workshop Link
workshop-url-placeholder = Enter Workshop link
thumbnail = Thumbnail
thumbnail-subtitle = Video thumbnail will be used if not set. Check if you have rights to the image. 4MB maximum.
change-thumbnail = Change
thumbnail-drop-to-change = Drag here to change thumbnail
reset-thumbnail = Use video thumbnail
description = Level Description
description-subtitle = 2,000 characters max.
description-placeholder = Enter description
tiles = Tile Count
tiles-subtitle = You can check your tile count by pressing Ctrl + F (⌘ + F) on the Level Editor.
tiles-placeholder = Enter tile count
bpm-subtitle = Enter the BPM of the music used.
min-bpm = Min BPM
max-bpm = Max BPM
expected-difficulty = Expected Difficulty
expected-difficulty-subtitle = This is only used for rating reference.
expected-difficulty-placeholder = Select difficulty
leave-alert = Cancel level submission and leave page?
limits = Restrictions
limits-subtitle = Select if there are restrictions for playing the level.
limits-neocosmos = Neo Cosmos DLC Needed
limits-seizure = Seizure Warning
submitting = Submitting level...
submit-success = Submit complete.
uploading = Uploading...
bpm = Music BPM
