song-length = Song Length
quality-featured = Featured
filter-artist = Artist
filter-music = Music Title
artists = Artist
quality-legendary = Legendary
workshop = Workshop
download = Download
report = Report
filter-creator = Creator
quality-listed = Listed
filter-quality = Category
creators = Creators
tiles = Tile Count
share = Share
search-placeholder = Search for levels, songs, artists, or creators.
bpm = BPM
sort-id-asc = Oldest first
sort-id-desc = Newest first
sort-difficulty-asc = Lowest diff. first
sort-difficulty-desc = Highest diff. first
link-copied = Level link copied!
filter-tags = Tags
filter-difficulty = { difficulty }
filter-difficulty-min = Min Diff.
filter-difficulty-max = Max Diff.
filter-tiles = Tiles
filter-tiles-min = Min Tiles
filter-tiles-max = Max Tiles
filter-bpm = BPM
filter-bpm-min = Min BPM
filter-bpm-max = Max BPM
difficulty = Lv.
reference-standard = Standard Level { $idx }
reference-base = Easiest Level { $idx }
note-reason = { $quality } 결정 사유
request-re-rate = 재책정 요청
request-re-rate-description = 의미 없이 재책정을 요청하면 계정이 제한될 수 있습니다.
request-re-rate-difficulty = 난이도
request-re-rate-difficulty-up = 더 높아야 함
request-re-rate-difficulty-down = 더 낮아야 함
request-re-rate-difficulty-unknown = 잘 모르겠음
request-re-rate-reason = 요청 사유
request-re-rate-reason-placeholder = 이 레벨이 재책정에 필요한 이유 입력
request-re-rate-submit = 요청
