song-length = Song Length
quality-featured = Featured
filter-artist = 아티스트
filter-music = 곡 제목
artists = Artist
quality-legendary = Legendary
workshop = Workshop
download = Download
report = Report
filter-creator = 제작자
quality-listed = Listed
filter-quality = 분류
creators = Creators
tiles = Tiles
share = Share
search-placeholder = Search the levels, songs, artists, and creators.
bpm = BPM
