song-length = Song Length
quality-featured = Featured
filter-artist = Artist
filter-music = Music Title
artists = Artist
quality-legendary = Legendary
workshop = Workshop
download = Download
report = Report
filter-creator = Creator
quality-listed = Listed
filter-quality = Category
creators = Creators
tiles = Tile Count
share = Share
search-placeholder = Search for levels, songs, artists, or creators.
bpm = BPM
sort-id-asc = Oldest first
sort-id-desc = Newest first
sort-difficulty-asc = Lowest lv. first
sort-difficulty-desc = Highest lv. first
link-copied = Level link copied!
