SWING = Swing
SLOW-description = This level is under 300BPM.
LONG-description = This level is 4 minutes or longer.
QUINTUPLET = Quintuplet
PSEUDO_P2 = Triple+ Pseudo
BEAT_P64 = 64+ Beats
MEMORIZATION-description = This level requires memorization.
FUNKY_BEAT-description = This level includes funky beats.
EPILEPSY_WARNING = Seizure Warning
NSFW-description = This level includes suggestive content.
SLOW = White Rabbit
GIMMICK = Gimmick
MAGIC_SHAPE = Magic Shape
QUINTUPLET-description = This level includes quintuplets.
LONG = 4+ Minutes
PSEUDO = Pseudo
NO_SPEED_CHANGES = No Speed Changes
SEPTUPLET-description = This level includes septuplets.
SPEED_CHANGES-description = This level uses music with speed changes.
SHORT = 1- Minute
MEMORIZATION = Memorization
SHORT-description = This level is 1 minute or shorter.
MAGIC_SHAPE-description = This level includes magic shapes.
SUDDEN_ACCELERATION = Burst
SPEED_CHANGES = Speed Changes
EPILEPSY_WARNING-description = This level includes flashing imagery that may trigger photosensitive seizures.
GALLOP = Sprint
BEAT_P64-description = This level includes 64+ beats.
SEPTUPLET = Septuplet
NO_TWIRLS = No Twirls
POLYRHYTHM = Polyrhythm
DLC = DLC
PSEUDO_P2-description = This level includes parts that requires you to press three or more keys at once.
GALLOP-description = This level includes sprints.
NSFW = NSFW
PSEUDO-description = This level includes parts that requires you to press two keys at once.
SWING-description = 20% of this level includes swing rhythm.
TRESILLO-description = This level includes tresillos.
TRESILLO = Tresillo
TRIPLET = Triplet
TRIPLET-description = This level includes triplets.
FUNKY_BEAT = Funky Beats
NO_TWIRLS-description = This level does not include twirls.
SUDDEN_ACCELERATION-description = This level includes sudden BPM accelerations.
NO_SPEED_CHANGES-description = This level keeps a constant speed.
DLC-description = This level requires the Neo Cosmos DLC.
POLYRHYTHM-description = This level includes polyrhythms.
GIMMICK-description = This level includes gimmicks.
LEGENDARY = Legendary
LEGENDARY-description = This level is highly recommended for its great track and VFX quality.
FEATURED = Featured
FEATURED-description = This level is recommended for its fair track quality.
