show-more = 더 보기
next = 다음으로
unknown = 알 수 없음
account-settings = 계정 설정
submit = 제출
rankings = 랭킹
upload-level = 레벨 투고
references = 기준
levels = 레벨
table-of-contents = 목차
my-levels = 내 레벨
back = 돌아가기
post-comment = 게시
cancel = 취소
manage-rating = 레벨 책정
