FUNKY_BEAT = 개박
SWING = 스윙
NO_TWIRLS-description = 이 레벨은 소용돌이를 포함하지 않습니다.
SLOW-description = 이 레벨은 300BPM 미만입니다.
LONG-description = 길이가 4분 이상인 레벨입니다.
QUINTUPLET = 다섯잇단
PSEUDO_P2 = 2+동타
BEAT_P64 = 64+비트
SUDDEN_ACCELERATION-description = 이 레벨은 BPM이 급격히 증가하는 부분을 포함합니다.
MEMORIZATION-description = 이 레벨은 암기를 요구합니다.
FUNKY_BEAT-description = 이 레벨은 괴상한 박자를 포함합니다.
EPILEPSY_WARNING = 광과민성 경고
NSFW-description = 이 레벨은 선정적이거나 잔인한 컨텐츠를 포함합니다.
SLOW = 흰 토끼
LEGENDARY = 레전드리
GIMMICK = 기믹
SWING-description = 이 레벨의 20% 이상에 스윙 박자가 포함되어 있습니다.
MAGIC_SHAPE = 마법진
QUINTUPLET-description = 이 레벨은 다섯잇단을 포함합니다.
TRESILLO-description = 이 레벨은 트레실로를 포함합니다.
LONG = 4분 이상
NO_SPEED_CHANGES-description = 이 레벨은 일정한 속도를 유지합니다.
PSEUDO = 동시 치기
TRESILLO = 트레실로
NO_SPEED_CHANGES = 속도 변경 없음
SEPTUPLET-description = 이 레벨은 일곱잇단을 포함합니다.
FEATURED-description = 트랙의 퀄리티가 준수하여 추천하는 레벨입니다.
SPEED_CHANGES-description = 이 레벨은 BPM이 변경되는 곡을 사용합니다.
SHORT = 1분 미만
FEATURED = 추천
MEMORIZATION = 암기
SHORT-description = 이 레벨은 1분 미만입니다.
MAGIC_SHAPE-description = 이 레벨은 마법진을 포함합니다.
DLC-description = 이 레벨은 Neo Cosmos DLC를 요구합니다.
SUDDEN_ACCELERATION = 급가속
SPEED_CHANGES = 변속
EPILEPSY_WARNING-description = 이 레벨은 깜박이는 장면 등 광과민성 발작을 발생할 수 있는 부분을 포함합니다.
GALLOP = 질주
LEGENDARY-description = 트랙과 이펙트의 퀄리티가 우수하여 적극 추천하는 레벨입니다.
BEAT_P64-description = 이 레벨은 64비트 이상을 포함합니다.
SEPTUPLET = 일곱잇단
NO_TWIRLS = 소용돌이 없음
POLYRHYTHM = 폴리리듬
POLYRHYTHM-description = 이 레벨은 폴리리듬을 포함합니다.
TRIPLET = 셋잇단
DLC = DLC
PSEUDO_P2-description = 이 레벨은 세 개 이상의 손가락으로 동시에 눌러야 하는 부분을 포함합니다.
GALLOP-description = 이 레벨은 질주를 포함합니다.
NSFW = NSFW
GIMMICK-description = 이 레벨은 기믹을 포함합니다.
PSEUDO-description = 이 레벨은 두 손가락으로 동시에 눌러야 하는 부분을 포함합니다.
TRIPLET-description = 이 레벨은 셋잇단을 포함합니다.
