nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: 'https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.3.1/bundles/@yarnpkg/plugin-after-install.js'

yarnPath: .yarn/releases/yarn-3.3.0.cjs

afterInstall: yarn postinstall
