apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adofai-gg
  name: frontend-beta
  labels:
    app: frontend-beta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-beta
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: frontend-beta
    spec:
      containers:
        - name: frontend-beta
          image: ghcr.io/adofai-gg/frontend:beta
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            limits:
              memory: '1Gi'
              cpu: '500m'
          livenessProbe:
            httpGet:
              port: 3000
              path: /healthcheck
          readinessProbe:
            httpGet:
              port: 3000
              path: /healthcheck
      imagePullSecrets:
        - name: registry-credentials
