apiVersion: v1
kind: Service
metadata:
  name: frontend-staging
  namespace: adofai-gg
spec:
  selector:
    app: frontend-staging
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
