song-length = Độ dài bài hát
quality-featured = Được đề xuất
filter-artist = Tác giả
filter-music = Tên bài hát
artists = Tác giả
quality-legendary = Huyền thoại
workshop = workshop
download = Tải về
report = Tố cáo
filter-creator = Người sáng tác
quality-listed = Được liệt kê theo chất lượng
filter-quality = Thể loại
creators = Người sáng tác
tiles = Số lượng nốt
share = Chia sẻ
search-placeholder = Tìm kiếm theo cấp độ, bài hát, nghệ sĩ hoặc người sáng tác
bpm = BPM
sort-id-asc = Sắp xếp theo ID tăng dần
sort-id-desc = Mới nhất
sort-difficulty-asc = Mức độ khó thấp nhất
sort-difficulty-desc = Theo thứ tự mức độ khó
link-copied = Đã sao chép liên kết !
difficulty = Độ khó
reference-standard = Dựa vào { $idx }
reference-base = Cấp độ dựa vào
filter-difficulty = { difficulty }
filter-tags = Thẻ/tags
filter-difficulty-min = Độ khó tối thiểu/thấp nhất
filter-difficulty-max = Độ khó tối đa
filter-tiles = Số lượng nốt
filter-tiles-min = Số lượng nốt tối thiểu/nhỏ nhất
filter-tiles-max = Số lượng nốt tối đa
filter-bpm = BPM
filter-bpm-min = BPM tối thiểu/nhỏ nhất
filter-bpm-max = BPM tối đa
note-reason = { $quality } 결정 사유
request-re-rate = 재책정 요청
request-re-rate-description = 의미 없이 재책정을 요청하면 계정이 제한될 수 있습니다.
request-re-rate-difficulty = 난이도
request-re-rate-difficulty-up = 더 높아야 함
request-re-rate-difficulty-down = 더 낮아야 함
request-re-rate-difficulty-unknown = 잘 모르겠음
request-re-rate-reason = 요청 사유
request-re-rate-reason-placeholder = 이 레벨이 재책정에 필요한 이유 입력
request-re-rate-submit = 요청
