tiles-subtitle = 레벨 에디터에서 Ctrl + F (⌘ + F)를 눌러 타일 번호를 확인할 수 있습니다.
music-title-subtitle = Nội dung nổi bật (feat.) cũng phải được đưa vào tiêu đề. Nếu bài hát không có trong danh sách, vui lòng tạo lại.
thumbnail-subtitle = 설정하지 않으면 영상 썸네일이 적용됩니다. 사진에 대한 권리가 있는지 확인하세요. 최대 4MB까지 업로드할 수 있습니다.
limits-subtitle = 레벨을 플레이하는 데 제약 사항이 있다면 선택하세요.
bpm-subtitle = 노래의 기본 BPM을 입력하세요.
upload-level-disclaimer = 다른 사람의 저작권이나 권리를 침해하면 등재가 거부되고 관련 법에 따라 처벌받을 수 있습니다.
leave-alert = 레벨 투고를 취소하고 이 페이지에서 나갈까요?
appending-title-subtitle = Nếu có tiêu đề cho cấp độ đó, chẳng hạn như (EX), (Nerfed), hãy nhập tiêu đề đó.
create-item = Tạo “{ $value }” mới
creator-alias-placeholder = 레벨 제작자 표시 이름 입력
creator-alias-subtitle = Nếu bạn cần xác định người tạo cấp độ theo cách khác nhau, chẳng hạn như theo tên nhóm, hãy nhập tên vào đây.
change-thumbnail = 바꾸기
preparing-upload = 업로드 준비 중...
workshop-url = Steam 창작마당 링크
video-url-subtitle = 레벨 전체를 녹화하고 YouTube에 업로드한 영상의 링크를 입력하세요.
submitting = 레벨을 제출하는 중...
music-title = Tên bài hát
limits-seizure = 광과민성 발작 가능성
video-url = YouTube 영상 링크
description = 레벨 설명
upload-level-title = { "." }Kéo và thả tệp zip
basic-information = Thông tin cơ bản
expected-difficulty-placeholder = 난도 선택
display-information = Hiển thị thông tin
expected-difficulty = 예상 난도
expected-difficulty-subtitle = 책정할 때의 참고용으로만 사용됩니다.
artists = Nhạc sĩ
create-level = Tạo cấp độ
video-url-placeholder = 영상 링크 입력
upload-level-subtitle = 혹은 이곳을 눌러 파일을 선택하세요
tiles-placeholder = 타일 수 입력
thumbnail = 썸네일
max-bpm = 최대 BPM
appending-title-placeholder = Nhập tiêu đề mô tả cấp độ tiếp theo
appending-title = Thêm tiêu đề
limits-neocosmos = Neo Cosmos DLC 필요
level-information = Thông tin cấp độ
workshop-url-placeholder = 창작마당 링크 입력
creators = Người sáng tác
reset-thumbnail = 영상 썸네일 쓰기
limits = 제약 사항
tiles = 레벨 타일 수
description-subtitle = 최대 2,000자까지 입력할 수 있습니다.
creator-alias = Tên hiển thị của người tạo cấp độ
description-placeholder = 설명 입력
add = Thêm vào
music-title-placeholder = Nhập tên bài hát...
submit-success = 레벨 제출이 완료되었습니다.
bpm = 기본 BPM
thumbnail-drop-to-change = 여기에 드래그해 썸네일 바꾸기
creators-subtitle = Chỉ những người đã đăng ký tài khoản trên ADOFAI.gg mới có thể thêm.
min-bpm = 최소 BPM
uploading = 업로드 중...
