song-length = 노래 길이
quality-featured = Featured
filter-artist = 아티스트
filter-music = 곡 제목
artists = 아티스트
quality-legendary = Legendary
workshop = 창작마당
download = 다운로드
report = 신고
filter-creator = 제작자
quality-listed = Listed
filter-quality = 분류
creators = 레벨 제작자
tiles = 타일 수
share = 공유
search-placeholder = 레벨, 노래, 아티스트, 제작자를 검색하세요.
bpm = BPM
sort-id-asc = 과거순
sort-id-desc = 최신순
sort-difficulty-asc = 난도 낮은 순
sort-difficulty-desc = 난도 높은 순
link-copied = 레벨 링크가 복사되었습니다!
difficulty = 난도
reference-standard = 기준 레벨 { $idx }
reference-base = 하한 레벨 { $idx }
filter-difficulty = { difficulty }
