tiles-subtitle = Bạn có thể kiểm tra số nốt bằng cách nhấn Ctrl + F (⌘ + F) trong trình chỉnh sửa cấp độ.
music-title-subtitle = Nội dung nổi bật (feat.) cũng phải được đưa vào tiêu đề. Nếu bài hát không có trong danh sách, vui lòng tạo lại.
thumbnail-subtitle = Nếu không được thiết lập, hình thu nhỏ của video sẽ được áp dụng ngẫu nhiên. Hãy đảm bảo bạn có quyền đối với ảnh. Bạn có thể tải lên tối đa 4MB.
limits-subtitle = Chọn nếu có bất kỳ hạn chế/giới hạn khi chơi cấp độ này.
bpm-subtitle = Nhập BPM cơ bản của bài hát.
upload-level-disclaimer = Nếu bạn vi phạm bản quyền hoặc quyền của người khác, cấp độ của bạn sẽ bị từ chối và bạn có thể phải chịu hình phạt theo quy định
leave-alert = Bạn có muốn hủy việc tải lên và thoát khỏi trang này không?
appending-title-subtitle = Nếu có tiêu đề cho cấp độ đó, chẳng hạn như (EX), (Nerfed), hãy nhập tiêu đề đó.
create-item = Tạo “{ $value }” mới
creator-alias-placeholder = 레벨 제작자 표시 이름 입력
creator-alias-subtitle = Nếu bạn cần xác định người tạo cấp độ theo cách khác nhau, chẳng hạn như theo tên nhóm, hãy nhập tên vào đây.
change-thumbnail = Thay đổi hình thu nhỏ
preparing-upload = Đang chuẩn bị tải lên...
workshop-url = Liên kết workshop Steam
video-url-subtitle = Nhập liên kết đến video bạn đã ghi lại toàn bộ cấp độ và tải lên YouTube.
submitting = Đang gửi cấp độ...
music-title = Tên bài hát
limits-seizure = Khả năng xảy ra cơn động kinh do nhạy cảm với ánh sáng
video-url = Liên kết video YouTube
description = Mô tả
upload-level-title = { "." }Kéo và thả tệp zip
basic-information = Thông tin cơ bản
expected-difficulty-placeholder = nhập mức độ khó của bạn
display-information = Hiển thị thông tin
expected-difficulty = Độ khó dự kiến
expected-difficulty-subtitle = cấp độ này chỉ được sử dụng để tham khảo
artists = Nhạc sĩ
create-level = Tạo cấp độ
video-url-placeholder = Nhập liên kết video
upload-level-subtitle = Nhấp vào đây để chọn một tập tin.
tiles-placeholder = Nhập số lượng nốt
thumbnail = Hình thu nhỏ
max-bpm = BPM tối đa
appending-title-placeholder = Nhập tiêu đề mô tả cấp độ tiếp theo
appending-title = Thêm tiêu đề
limits-neocosmos = Cấp độ này cần DLC Neo cosmos!
level-information = Thông tin cấp độ
workshop-url-placeholder = Nhập liên kết đến workshop
creators = Người sáng tác
reset-thumbnail = Tải lại/cài lại hình thu nhỏ video
limits = Hạn chế/giới hạn
tiles = Số nốt cấp độ
description-subtitle = Bạn có thể nhập tối đa 2.000 ký tự.
creator-alias = Tên hiển thị của người tạo cấp độ
description-placeholder = Nhập mô tả
add = Thêm vào
music-title-placeholder = Nhập tên bài hát...
submit-success = Đã hoàn tất việc tải lên
bpm = BPM mặc định
thumbnail-drop-to-change = Kéo vào đây để thay đổi hình thu nhỏ
creators-subtitle = Chỉ những người đã đăng ký tài khoản trên ADOFAI.gg mới có thể thêm.
min-bpm = BPM tối thiểu
uploading = Đang tải lên...
