song-length = 노래 길이
quality-featured = Featured
filter-artist = 아티스트
filter-music = 곡 제목
artists = 아티스트
quality-legendary = Legendary
workshop = 창작마당
download = 다운로드
report = 신고
filter-creator = 제작자
quality-listed = Listed
filter-quality = 분류
creators = 레벨 제작자
tiles = 타일 수
share = 공유
search-placeholder = 레벨, 노래, 아티스트, 제작자를 검색하세요.
bpm = BPM
