FUNKY_BEAT = Nhịp sôi nổi
SWING = 스윙
NO_TWIRLS-description = 이 레벨은 소용돌이를 포함하지 않습니다.
SLOW-description = 이 레벨은 300BPM 미만입니다.
LONG-description = 길이가 4분 이상인 레벨입니다.
QUINTUPLET = 다섯잇단
PSEUDO_P2 = 2+동타
BEAT_P64 = Nhịp 64+
SUDDEN_ACCELERATION-description = 이 레벨은 BPM이 급격히 증가하는 부분을 포함합니다.
MEMORIZATION-description = 이 레벨은 암기를 요구합니다.
FUNKY_BEAT-description = Cấp độ này chứa nhịp lẻ/sôi nổi.
EPILEPSY_WARNING = Chú ý hiệu ứng
NSFW-description = 이 레벨은 선정적이거나 잔인한 컨텐츠를 포함합니다.
SLOW = 흰 토끼
GIMMICK = Cơ chế
SWING-description = 이 레벨의 20% 이상에 스윙 박자가 포함되어 있습니다.
MAGIC_SHAPE = 마법진
QUINTUPLET-description = 이 레벨은 다섯잇단을 포함합니다.
TRESILLO-description = 이 레벨은 트레실로를 포함합니다.
LONG = 4분 이상
NO_SPEED_CHANGES-description = 이 레벨은 일정한 속도를 유지합니다.
PSEUDO = 동시 치기
TRESILLO = 트레실로
NO_SPEED_CHANGES = 속도 변경 없음
SEPTUPLET-description = 이 레벨은 일곱잇단을 포함합니다.
SPEED_CHANGES-description = 이 레벨은 BPM이 변경되는 곡을 사용합니다.
SHORT = 1분 미만
MEMORIZATION = 암기
SHORT-description = 이 레벨은 1분 미만입니다.
MAGIC_SHAPE-description = 이 레벨은 마법진을 포함합니다.
DLC-description = Cấp độ này yêu cầu DLC Neo Cosmos.
SUDDEN_ACCELERATION = 급가속
SPEED_CHANGES = 변속
EPILEPSY_WARNING-description = Cấp độ này bao gồm các hiệu ứng có thể gây co giật nhạy cảm với ánh sáng, chẳng hạn như cảnh nhấp nháy.
GALLOP = Nhanh
BEAT_P64-description = Cấp độ này bao gồm 64 beats trở lên.
SEPTUPLET = 일곱잇단
NO_TWIRLS = 소용돌이 없음
POLYRHYTHM = 폴리리듬
POLYRHYTHM-description = 이 레벨은 폴리리듬을 포함합니다.
TRIPLET = 셋잇단
DLC = DLC
PSEUDO_P2-description = 이 레벨은 세 개 이상의 손가락으로 동시에 눌러야 하는 부분을 포함합니다.
GALLOP-description = Cấp độ này liên quan đến beat nhanh
NSFW = NSFW
GIMMICK-description = Cấp độ này chứa các cơ chế phức tạp
PSEUDO-description = 이 레벨은 두 손가락으로 동시에 눌러야 하는 부분을 포함합니다.
TRIPLET-description = 이 레벨은 셋잇단을 포함합니다.
LEGENDARY = 레전드리
LEGENDARY-description = 트랙과 이펙트의 퀄리티가 우수하여 적극 추천하는 레벨입니다.
FEATURED = 추천
FEATURED-description = 트랙의 퀄리티가 준수하여 추천하는 레벨입니다.
