FUNKY_BEAT = Nhịp sôi nổi
SWING = 스윙
NO_TWIRLS-description = Cấp độ này không có xoáy.
SLOW-description = 이 레벨은 300BPM 미만입니다.
LONG-description = Các cấp độ dài hơn 4 phút.
QUINTUPLET = 다섯잇단
PSEUDO_P2 = 2+Pseudo
BEAT_P64 = Nhịp 64+
SUDDEN_ACCELERATION-description = 이 레벨은 BPM이 급격히 증가하는 부분을 포함합니다.
MEMORIZATION-description = Cấp độ này đòi hỏi phải ghi nhớ.
FUNKY_BEAT-description = Cấp độ này chứa nhịp lẻ/sôi nổi.
EPILEPSY_WARNING = Chú ý hiệu ứng
NSFW-description = Cấp độ này chứa nội dung khiêu dâm hoặc bạo lực.
SLOW = 흰 토끼
GIMMICK = Cơ chế
SWING-description = 이 레벨의 20% 이상에 스윙 박자가 포함되어 있습니다.
MAGIC_SHAPE = Vòng tròn Magic.
QUINTUPLET-description = 이 레벨은 다섯잇단을 포함합니다.
TRESILLO-description = 이 레벨은 트레실로를 포함합니다.
LONG = 4 phút hoặc hơn
NO_SPEED_CHANGES-description = Cấp độ này duy trì tốc độ không đổi.
PSEUDO = Pseudo
TRESILLO = 트레실로
NO_SPEED_CHANGES = Không thay đổi tốc độ
SEPTUPLET-description = 이 레벨은 일곱잇단을 포함합니다.
SPEED_CHANGES-description = 이 레벨은 BPM이 변경되는 곡을 사용합니다.
SHORT = 1분 미만
MEMORIZATION = Ghi nhớ
SHORT-description = 이 레벨은 1분 미만입니다.
MAGIC_SHAPE-description = Cấp độ này bao gồm một vòng tròn Magic.
DLC-description = Cấp độ này yêu cầu DLC Neo Cosmos.
SUDDEN_ACCELERATION = 급가속
SPEED_CHANGES = 변속
EPILEPSY_WARNING-description = Cấp độ này bao gồm các hiệu ứng có thể gây co giật nhạy cảm với ánh sáng, chẳng hạn như cảnh nhấp nháy.
GALLOP = Nhanh
BEAT_P64-description = Cấp độ này bao gồm 64 beats trở lên.
SEPTUPLET = 일곱잇단
NO_TWIRLS = Không có xoáy
POLYRHYTHM = Đa nhịp điệu
POLYRHYTHM-description = Cấp độ này bao gồm nhiều nhịp điệu.
TRIPLET = 셋잇단
DLC = DLC
PSEUDO_P2-description = Cấp độ này bao gồm các khu vực yêu cầu bạn phải ấn bằng ba ngón tay trở lên cùng lúc.
GALLOP-description = Cấp độ này liên quan đến beat nhanh
NSFW = NSFW
GIMMICK-description = Cấp độ này chứa các cơ chế phức tạp
PSEUDO-description = Cấp độ này bao gồm các khu vực yêu cầu bạn phải ấn bằng hai ngón tay cùng một lúc.
TRIPLET-description = 이 레벨은 셋잇단을 포함합니다.
LEGENDARY = 레전드리
LEGENDARY-description = 트랙과 이펙트의 퀄리티가 우수하여 적극 추천하는 레벨입니다.
FEATURED = 추천
FEATURED-description = 트랙의 퀄리티가 준수하여 추천하는 레벨입니다.
