FUNKY_BEAT = Nhịp sôi nổi
SWING = xoay
NO_TWIRLS-description = Cấp độ này không có xoáy.
SLOW-description = Cấp độ này ít hơn 300 BPM.
LONG-description = Các cấp độ dài hơn 4 phút.
QUINTUPLET = Năm nút
PSEUDO_P2 = 2+Pseudo
BEAT_P64 = Nhịp 64+
SUDDEN_ACCELERATION-description = cấp độ này tăng tốc mạnh về BPM.
MEMORIZATION-description = Cấp độ này đòi hỏi phải ghi nhớ.
FUNKY_BEAT-description = Cấp độ này chứa nhịp lẻ/sôi nổi.
EPILEPSY_WARNING = Chú ý hiệu ứng
NSFW-description = Cấp độ này chứa nội dung khiêu dâm hoặc bạo lực.
SLOW = Chậm.
GIMMICK = Cơ chế
SWING-description = Hơn 20% các cấp độ này chứa các nốt xoay.
MAGIC_SHAPE = Vòng tròn Magic.
QUINTUPLET-description = Cấp độ này bao gồm năm nốt cùng lúc.
TRESILLO-description = Cấp độ này chứa tresillo.
LONG = 4 phút hoặc hơn
NO_SPEED_CHANGES-description = Cấp độ này duy trì tốc độ không đổi.
PSEUDO = Pseudo
TRESILLO = tresillo
NO_SPEED_CHANGES = Không thay đổi tốc độ
SEPTUPLET-description = Cấp độ này bao gồm bảy nốt cùng lúc.
SPEED_CHANGES-description = Cấp độ này sử dụng các khu vực có BPM thay đổi.
SHORT = chưa tới 1 phút.
MEMORIZATION = Ghi nhớ
SHORT-description = Cấp độ này tốn chưa tới 1 phút.
MAGIC_SHAPE-description = Cấp độ này bao gồm một vòng tròn Magic.
DLC-description = Cấp độ này yêu cầu DLC Neo Cosmos.
SUDDEN_ACCELERATION = tăng tốc đột ngột.
SPEED_CHANGES = Tốc độ thay đổi
EPILEPSY_WARNING-description = Cấp độ này bao gồm các hiệu ứng có thể gây co giật nhạy cảm với ánh sáng, chẳng hạn như cảnh nhấp nháy.
GALLOP = Nhanh
BEAT_P64-description = Cấp độ này bao gồm 64 beats trở lên.
SEPTUPLET = bảy nốt
NO_TWIRLS = Không có xoáy
POLYRHYTHM = Đa nhịp điệu
POLYRHYTHM-description = Cấp độ này bao gồm nhiều nhịp điệu.
TRIPLET = 3 nốt cùng lúc.
DLC = DLC
PSEUDO_P2-description = Cấp độ này bao gồm các khu vực yêu cầu bạn phải ấn bằng ba ngón tay trở lên cùng lúc.
GALLOP-description = Cấp độ này liên quan đến beat nhanh
NSFW = NSFW
GIMMICK-description = Cấp độ này chứa các cơ chế phức tạp.
PSEUDO-description = Cấp độ này bao gồm các khu vực yêu cầu bạn phải ấn bằng hai ngón tay cùng một lúc.
TRIPLET-description = Cấp độ này chứa 3 nốt cùng lúc.
LEGENDARY = Huyền thoại
LEGENDARY-description = Cấp độ này rất được khuyến khích vì chất lượng của các bản nhạc và hiệu ứng rất tuyệt vời.
FEATURED = gợi ý
FEATURED-description = cấp độ này được khuyến khích vì chất lượng cấp độ ở mức khá
