song-length = 歌曲长度
quality-featured = 推荐
filter-artist = 作曲家
filter-music = 曲名
artists = 作曲家
quality-legendary = 传奇
workshop = 创意工坊
download = 下载
report = 举报
filter-creator = 谱师
quality-listed = 上架
filter-quality = 分类
creators = 谱师
tiles = 物量
share = 分享
search-placeholder = 搜索关卡、歌曲、作曲家、谱师
bpm = BPM
sort-id-asc = 과거순
sort-id-desc = 최신순
sort-difficulty-asc = 난도 낮은 순
sort-difficulty-desc = 난도 높은 순
