thumbnail = 封面
change-thumbnail = 替换
tiles-subtitle = 您可以在关卡编辑器中使用 Ctrl + F (⌘ + F)快捷键来查看您的总物量.
music-title-subtitle = 特邀制作人(feat.)请在标题中注明，如果歌曲不在列表中，请先进行注册。
thumbnail-subtitle = 如果您未单独上传封面将直接使用视频封面，请确认您有封面使用权，文件大小不能超过4MB.
limits-subtitle = 如果这个关卡存在任何限制，请选择。
bpm-subtitle = 输入这个音乐的BPM.
upload-level-disclaimer = 侵犯他人权利可能会导致您的关卡被拒绝，并追究您的法律责任。
leave-alert = 您确定要离开这个页面吗?您的编辑不会被保存
appending-title-subtitle = 如果谱面有（EX）、（Nerfed）等副标题，请输入。
create-item = 将“{ $value }”注册为新条目
creator-alias-placeholder = 输入制作人别名
creator-alias-subtitle = 如果您需要以其他名义显示在制作人栏（比如团队名），请输入。
preparing-upload = 正在准备上传......
workshop-url = Steam创意工坊链接
video-url-subtitle = 输入您完整关卡的视频链接.
submitting = 正在上传关卡......
music-title = 歌名
limits-seizure = 光敏癫痫警告
video-url = YouTube 视频链接
description = 关卡说明
upload-level-title = 将{ "." }zip文件拖动到此处以上传
basic-information = 基本信息
expected-difficulty-placeholder = 选择难度等级
display-information = 显示信息
expected-difficulty = 您期待的难度等级
expected-difficulty-subtitle = 这只用于评级参考.
artists = 作曲家
create-level = 谱面投稿
video-url-placeholder = 输入视频链接
upload-level-subtitle = 或点击这里选择文件
tiles-placeholder = 输入总物量
max-bpm = 最大 BPM
appending-title-placeholder = 输入歌曲标题，包含谱面的其他详细信息
appending-title = 谱面副标题
limits-neocosmos = 需要Neo Cosmos DLC
level-information = 谱面信息
workshop-url-placeholder = 输入Steam创意工坊链接
creators = 谱师
reset-thumbnail = 使用视频封面
limits = 限制
tiles = 总物量
description-subtitle = 限制最大2000字.
creator-alias = 制作人别名
description-placeholder = 输入说明
add = 添加
music-title-placeholder = 请输入曲名...
submit-success = 上传成功。
bpm = 音乐BPM
thumbnail-drop-to-change = 拖拽到此处以修改封面
creators-subtitle = 只有ADOFAI.gg的注册用户可以添加。
min-bpm = 最小 BPM
uploading = 正在上传......
