song-length = 歌曲长度
quality-featured = 推荐
filter-artist = 作曲家
filter-music = 曲名
artists = 作曲家
quality-legendary = 传奇
workshop = 创意工坊
download = 下载
report = 举报
filter-creator = 谱师
quality-listed = 上架
filter-quality = 分类
creators = 谱师
tiles = 物量
share = 分享
search-placeholder = 搜索谱面、歌曲、作曲家、谱师。
bpm = BPM
sort-id-asc = 时间由旧到新排序
sort-id-desc = 时间由新到旧排序
sort-difficulty-asc = 难度低到高排序
sort-difficulty-desc = 难度高到低排序
link-copied = 关卡链接已复制!
difficulty = 难度
reference-standard = 标准关卡 { $idx }
reference-base = 最简单的关卡· { $idx }
filter-difficulty = { difficulty }
filter-tags = 标签
filter-difficulty-min = 最低等级
filter-difficulty-max = 最高等级
filter-tiles = 物量
filter-tiles-min = 最少物量
filter-tiles-max = 最多物量
filter-bpm = BPM
filter-bpm-min = 最小BPM
filter-bpm-max = 最大BPM
