unknown = Unknown
show-more = Show more
next = Next
nav-links = 
    .levels = Levels
    .rankings = Rankings
    .references = References
account-settings = Account settings
upload-level = Submit level
submit = Submit
table-of-contents = Table of Contets

main-section-recent-legendary-levels = Recent Legendary Levels
main-link-usage = Forum Usage Guide
main-link-quality-guideline = Quality Guidelines

level-song-length = Song Length
level-quality-featured = Featured
level-filter-artist = Artist
level-filter-music = Music Title
level-artists = Artist
level-quality-legendary = Legendary
level-workshop = Workshop
level-download = Download
level-report = Report
level-filter-creator = Creator
level-quality-listed = Listed
level-filter-quality = Category
level-creators = Creators
level-tiles = Tile Count
level-share = Share
level-search-placeholder = Search for levels, songs, artists, or creators.
level-bpm = BPM
level-sort-id-asc = Oldest first
level-sort-id-desc = Newest first
level-sort-difficulty-asc = Lowest diff. first
level-sort-difficulty-desc = Highest diff. first
level-link-copied = Level link copied!
level-filter-tags = Tags
level-filter-difficulty = { difficulty }
level-filter-difficulty-min = Min Diff.
level-filter-difficulty-max = Max Diff.
level-filter-tiles = Tiles
level-filter-tiles-min = Min Tiles
level-filter-tiles-max = Max Tiles
level-filter-bpm = BPM
level-filter-bpm-min = Min BPM
level-filter-bpm-max = Max BPM
level-difficulty = Lv.
level-reference-standard = Standard Level { $idx }
level-reference-base = Easiest Level { $idx }

tag-SWING = Swing
    .description = 20% of this level includes swing rhythm.
tag-QUINTUPLET = Quintuplet
    .description = This level includes quintuplets.
tag-PSEUDO_P2 = Triple+ Pseudo
    .description = This level includes parts that requires you to press three or more keys at once.
tag-BEAT_P64 = 64+ Beats
    .description = This level includes 64+ beats.
tag-EPILEPSY_WARNING = Seizure Warning
    .description = This level includes flashing imagery that may trigger photosensitive seizures.
tag-SLOW = White Rabbit
    .description = This level is under 300BPM.
tag-GIMMICK = Gimmick
    .description = This level includes gimmicks.
tag-MAGIC_SHAPE = Magic Shape
    .description = This level includes magic shapes.
tag-LONG = 4+ Minutes
    .description = This level is 4 minutes or longer.
tag-PSEUDO = Pseudo
    .description = This level includes parts that requires you to press two keys at once.
tag-NO_SPEED_CHANGES = No Speed Changes
    .description = This level keeps a constant speed.
tag-SHORT = 1- Minute
    .description = This level is 1 minute or shorter.
tag-MEMORIZATION = Memorization
    .description = This level requires memorization.
tag-SUDDEN_ACCELERATION = Burst
    .description = This level includes sudden BPM accelerations.
tag-SPEED_CHANGES = Speed Changes
    .description = This level uses music with speed changes.
tag-GALLOP = Sprint
    .description = This level includes sprints.
tag-SEPTUPLET = Septuplet
    .description = This level includes septuplets.
tag-NO_TWIRLS = No Twirls
    .description = This level does not include twirls.
tag-POLYRHYTHM = Polyrhythm
    .description = This level includes polyrhythms.
tag-DLC = DLC
    .description = This level requires the Neo Cosmos DLC.
tag-NSFW = NSFW
    .description = This level includes suggestive content.
tag-TRESILLO = Tresillo
    .description = This level includes tresillos.
tag-TRIPLET = Triplet
    .description = This level includes triplets.
tag-FUNKY_BEAT = Funky Beats
    .description = This level includes funky beats.
tag-LEGENDARY = Legendary
    .description = This level is highly recommended for its great track and VFX quality.
tag-FEATURED = Featured
    .description = This level is recommended for its fair track quality.
