name: Test Build

on:
  pull_request:

permissions:
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup pnpm
        run: corepack enable
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: |
          echo '//npm.pkg.github.com/:_authToken=${GH_NPM_TOKEN}' >> .npmrc
          GH_NPM_TOKEN="${{ secrets.GITHUB_TOKEN }}" pnpm install --frozen-lockfile
      - name: Build
        run: |
          pnpm build
          pnpm pack
          cp adofai-gg-*.tgz package.tgz
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.tgz
          if-no-files-found: error
