name: Test Build

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Setup yarn
        run: corepack enable
      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(C:\Users\paring\Documents\Programming\adofai-gg-web\.yarn\cache)" >> $GITHUB_ENV
      - name: Cache yarn dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn build
          yarn pack
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package.tgz
          if-no-files-found: error
