name: Deploy Beta

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: adofai-gg/frontend

on:
  push:
    branches:
      - 'beta'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v1
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:beta
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            API_ENDPOINT=${{ secrets.STAGING_API_ENDPOINT }}
            OPENGRAPH_ENDPOINT=${{ secrets.STAGING_OPENGRAPH_ENDPOINT }}
            DISCORD_INVITE=https://discord.gg/adofaigg
            SUPPORT_MAIL=support@adofai.gg
            GTM_ID=GTM-WDQRN9M
            GA_ID=G-3BKXMVNJYQ
      - name: Send update signal to kubernetes
        run: bash ./deploy/staging/deploy-beta.sh
        env:
          API_ENDPOINT: ${{ secrets.STAGING_KUBERNETES_API_ENDPOINT }}
          API_TOKEN: ${{ secrets.STAGING_KUBERNETES_API_TOKEN }}
