name: Deploy Staging

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: adofai-gg/frontend

on:
  push:
    branches:
      - 'new-rewrite'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:staging
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          platforms: ${{ steps.buildx.outputs.platforms }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            API_ENDPOINT=${{ secrets.STAGING_API_ENDPOINT }}
            OPENGRAPH_ENDPOINT=${{ secrets.STAGING_OPENGRAPH_ENDPOINT }}
            DISCORD_INVITE=https://discord.gg/adofaigg
            SUPPORT_MAIL=support@adofai.gg
            SENTRY_ENV=staging
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_URL=${{ secrets.SENTRY_URL }}
