name: Docker

on:
  push:
  release:
    types:
      - published

permissions:
  packages: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: cr.afg.ink
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cr.afg.ink/forum/web
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GH_NPM_TOKEN=${{ secrets.GITHUB_TOKEN }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
