name: Docker

on:
  push:
  release:
    types:
      - published
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/adofai-gg/adofai-gg-web
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            API_ENDPOINT=https://adofai.gg
            OPENGRAPH_ENDPOINT=https://og.afg.ink
            DISCORD_INVITE=https://discord.gg/adofaigg
            SUPPORT_MAIL=support@adofai.gg
            SENTRY_ENV=staging
            SENTRY_ORG=${{ secrets.SENTRY_ORG }}
            SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_URL=${{ secrets.SENTRY_URL }}
