name: Lint

on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Setup yarn
        run: corepack enable
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
